# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SmartLock_IOS_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'GoogleSignIn'

  # Pods for SmartLock_IOS_app

end
